apiVersion: batch/v1
kind: Job
metadata:
  name: bike-store-job
spec:
  template:
    spec:
      containers:
      - name: bike-store-job
        image: yash5090/bike-store:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
